host: 192.168.91.50
server:
  port: 8001
rpc:
  server:
    port: 7001
    token: fightTigersTonight
  client:
    remote-api-packages: "com.xmg.remoteApi."
    token: fightTigersTonight
spring:
  profiles:
    active: u55
  datasource:
    url: jdbc:mysql://${host}:3306/rpc-test-product?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: ${host}:8848
        enabled: true
        username: nacos
        password: laosijiddd
  application:
    name: product
  jpa:
    show-sql: false
    properties:
      hibernate:
        #打开hibernate统计信息
        generate_statistics: false
        #自动建表
        hbm2ddl.auto: update
        #格式化sql
        format_sql: true
        #数据库方言
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        max_fetch_depth: 1
        jdbc:
          batch_size: 100  #IDENTITY主键策略 插入时不支持batch
    open-in-view: false
logging:
  level:
    root: info
    xmg.server.handler.ServerHandler: debug
    xmg.client.handler.ClientHandler: debug
    xmg.client.handler.RpcFuture: debug
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_group
  service:
    vgroupMapping:
      my_test_group: default
      application-id: seata-server
  registry:
    type: nacos
    nacos:
      server-addr: ${host}:8848
      group: DEFAULT_GROUP
      username: nacos
      password: laosijiddd
  config:
    type: nacos
    nacos:
      server-addr: ${host}:8848
      group : DEFAULT_GROUP
      username: nacos
      password: laosijiddd
#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: my_test_group
#  service:
#    vgroupMapping:
#      my_test_group: default
#      application-id: seata-server
#    grouplist:
#      default: test:8091
