server:
  port: 8000
rpc:
  client:
    remote-api-packages: "com.xmg.remoteApi."
    token: fightTigersTonight
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.10:8848
        enabled: false
  application:
    name: consumer
logging:
  level:
    root: info
    xmg.client.handler.ClientHandler: debug
    xmg.client.handler.RpcFuture: debug