server:
  port: 8000
rpc:
  server:
    port: 7000
  client:
    remote-api-packages: "com.xmg.remoteApi."
spring:
  profiles:
    active:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.10:8848
  application:
    name: provider
logging:
  level:
    root: info
    xmg.server.handler.ServerHandler: debug
    xmg.client.handler.ClientHandler: debug
    xmg.client.handler.RpcFuture: debug