server:
  port: 8001
rpc:
  server:
    port: 7001
    token: fightTigersTonight
  client:
    remote-api-packages: "com.xmg.remoteApi."
spring:
  profiles:
    active: test1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.10:8848
        enabled: false
  application:
    name: provider
logging:
  level:
    root: info
    xmg.server.handler.ServerHandler: debug
    xmg.client.handler.ClientHandler: debug
    xmg.client.handler.RpcFuture: debug