server:
  port: 8001
rpc:
  server:
    port: 7001
    token: fightTigersTonight
  client:
    remote-api-packages: "com.xmg.remoteApi."
    token: fightTigersTonight
spring:
  profiles:
    active: test1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.10:8848
        enabled: false
  application:
    name: provider
  jpa:
    show-sql: false
    properties:
      hibernate:
        #打开hibernate统计信息
        generate_statistics: false
        #自动建表
        hbm2ddl.auto: update
        #格式化sql
        format_sql: true
        #数据库方言
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        max_fetch_depth: 1
        jdbc:
          batch_size: 100  #IDENTITY主键策略 插入时不支持batch
    open-in-view: false
logging:
  level:
    root: info
    xmg.server.handler.ServerHandler: debug
    xmg.client.handler.ClientHandler: debug
    xmg.client.handler.RpcFuture: debug