spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.10:8848
        namespace: 7e0d2cbd-9321-4964-ba80-59bb228b8776
        enabled: true
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/rpc-test-account?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 1234
server:
  port: 8002
rpc:
  server:
    port: 7002

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: mall_tx_group
  service:
    vgroupMapping:
      mall_tx_group: default
      application-id: seata-server
    grouplist:
      default: 192.168.0.10:8091